export const breakfast_menu = [
  {
    label: "BREAK FAST",
    menus: [
      {
        name: "TOAST",
        description: "Country white, dark wheat, Kalamata olive, Raisin Walnut",
        price: "5",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/toast.jpeg",
      },
      {
        name: "Bacon & Egg Press",
        description: "Chilli jam, aioli, spinach & cheddar.",
        price: "9.00",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "Breakfast Wrap",
        description: "Egg, hash, chilli jam, cheese, spinach",
        price: "10.00",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "menus/breakfastWrap.jpeg",
      },
      {
        name: "Croissant",
        description: "Ham, cheese or cheese tomato.",
        price: "9.00",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "Parmesan Scrambled Eggs",
        description: "Dark miche & truffle oil.",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "Poached, Scrambled or Fried Eggs",
        description: "Sonoma Sourdough.",
        price: "10",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "This is me Brekkie",
        description:
          "Two eggs, sourdough, mushroom, bacon, avocado & potato hash.",
        price: "23",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "menus/thisIsBreakie.jpeg",
      },
      {
        name: "AVOCADO SMASH",
        description:
          "Yarra Feta citrus, roasted peanut, coriander, poached egg",
        price: "13",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/avoTomatoToast.jpeg",
      },
      {
        name: "THIS IS ME BREKKIE",
        description:
          "Crispy bacon, poached egg, potato rosti, avocado, butter mushrooms, sourdough",
        price: "22",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/thisIsBreakie.jpeg",
      },
      {
        name: "Toasted Muesli",
        description: "Seasonal fruits, yoghurt",
        price: "11",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "Zucchini Fritters",
        description: "Bacon, crème cheese, chilli jam, cucumber.",
        price: "21",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "EGGS ON TOAST",
        description: "Fried, scrambled, Poached",
        price: "10",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "EXTRAS",
        description:
          "Pendle Hill Bacon, sauntéed spinach, butter mushrooms, potato rosti, two eggs, avocado",
        price: "4",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
    ],
  },
];

export const lunch_menu = [
  {
    label: "SMALL THINGS",
    menus: [
      {
        name: "CRISPY PORK BELLY RICE PAPER ROLL",
        description: "Vermicelli Cucumber Pickled Carrot Peanut Sauce (2pc)",
        price: "8",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "LEMONGRASS BEEF RICE PAPER ROLLS W CUCUMBER",
        description: "Minted Iceberg Pickled Carrot Peanut Sauce (2pc)",
        price: "8",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "SEASONAL VEGETABLES & PUFF TOFU AVOCADO RICE PAPER ROLL (VG) (2PC)",
        description: "",
        price: "8",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "HERBY CHICKEN SESAME RICE PAPER ROLL W CUCUMBER PICICLED CARROT MAYO (2PC)",
        description: "",
        price: "8",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "HA DOAN’ S CHICKEN SPRING ROLLS NUOC CHAM (3PC)",
        description: "",
        price: "8",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "ROASTED DUCK RICE PAPER ROLL CUCUMBER VERMICELLI (2PC)",
        description: "",
        price: "9",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
    ],
  },
  {
    label: "VERMICELLI/SALADS",
    menus: [
      {
        name: "LOTUS STORY SALAD SHAVED CABBAGE",
        description:
          "Pickled Radish Peanuts Crispy Onion Aromatic Herbs Nuoc Cham – Crispy Tofu (GF) – Poached Chicken",
        price: "16",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "GRILLED BEEF AND SPRING ROLL VERMICELLI MINTED",
        description: "Iceberg Picicled Carrots Peanuts Scallions",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "menus/beefVermiceli.jpeg",
      },
      {
        name: "HERBY CHICON SUGARCANE PRAWN VERMICELLI MINTED",
        description: "Iceberg Picjcled Carrot Peanuts Scallions",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "CRISPY TOFU & SEASONAL AVOCADO",
        description: "Bean Sprouts Peanuts Sweet Soy Sesame Dressing (Vg)",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "HANOI TURMERIC FISH AND AVOCADO MINTED",
        description: "Iceberg Picjcled Carrots Peanuts Scallions",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "ROASTED PORK BELLY VERMICELLI AROMATIC HERBS SCALLIONS PEANUTS",
        description: "",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "FRESH BAKED BAGUETTES",
        description:
          "All Served With Fresh Mix Leaves Pickled Carrots Home Made Butter Peanut Sauce (P) Or House Soy (S) Original/Multigrain Bread, Chilli Or Coriander Optional",
        price: "11",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
    ],
  },
  {
    label: "NOODLES",
    menus: [
      {
        name: "HA DOAN’S 28 HOUR “PHO” BROTH – SLICED GRAIN FED BEEF I POACHED CHICKEN NOODLES AROMATIC HERBS (GF)",
        description: "",
        price: "15 / 17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "COMBINATION – BRISKET, SLICED BEEF, BEEF BALLS",
        description: "",
        price: "19",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "menus/combination.jpeg",
      },
      {
        name: "LOTUS STORY CHICKEN LAKSA RICE VERMICELLI & EGG NOODLE PUFF TOFU HINT AND FRIED SHALLOTS",
        description: "",
        price: "15",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "SPICY XO NOODLES CHICKEN, FRIED EGG, SEASONAL VEG CABBAGE HOUSE SOY EGG NOODLE HOUSE CHILLI OIL",
        description: "",
        price: "18",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "SESAME BEEF HOFUN, GAI LAN, CHIVES, BEANSPOUTS, HOUSE DARK SOY",
        description: "",
        price: "20",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "LOTUS STORY SINGAPORE NOODLES HOUSE CURRY PASTE",
        description: "Seasonal Vegetables Thin Rice Noodles Puff Tofu/Chicken",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
    ],
  },
  {
    label: "Rice",
    menus: [
      {
        name: "Crispy Skin Chicken",
        description:
          "Twice cooked boneless chicken Maryland, tomato rice, nuoc cham",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "Lotus Story Pork Chop Rice",
        description: "Lemongrass pork chop, tomato rice, nuoc cham",
        price: "18",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "Lotus Story Rice Bowls",
        description:
          "Poke bowl seven seasonal condiments citrus nuoc cham turmeric dill yoghurt.",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/RiceBowl.jpeg",
      },
      {
        name: "Chicken Curry Rice (Mild)",
        description:
          "Potato carrots shaved onion shallots jasmine rice/baguette.",
        price: "18",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/curry.jpeg",
      },
      {
        name: "Saigon Star Anise Beef Stew",
        description:
          "Curry carrots crispy onion thai basil jasmine rice/baguette.",
        price: "16",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "menus/beefStew.jpeg",
      },
      {
        name: "Gong Bao Tofu",
        description:
          "Capsicum cashew seasonal greens sichuan chilli scallions garlic chives (vg).",
        price: "14",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "Hoi An Tumeric White Cut Chicken",
        description:
          "Hoi an chilli sambal rau ram mint crispy shallots seasonal pickles (gf).",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "menus/hoian_chicken.jpeg",
      },
      {
        name: "Lotus Story Original Fried Rice",
        description: "Seasonal greens cherry tomato onion spicy house xo.",
        price: "16",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/fried_rice.jpeg",
      },
      {
        name: "Angus Steak Fried Rice",
        description: "Seasonal greens, egg, house soy",
        price: "20",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "Shaking Beef",
        description: "Edamame onion pink ranch pickles jasmine rice.",
        price: "18",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "menus/shakingBeef.jpeg",
      },
    ],
  },
];

export const coffee_menu = [
  {
    label: "COFFEE",
    menus: [
      {
        name: "COFFEE",
        description: "Extras: Shot / Syrup / Decaf / Soy",
        price: "4 / 4.5",
        sub_price: "0.5",
        count: 0,
        option: "",
        imgSrc: "/menus/cappucino.jpeg",
      },
      {
        name: "TEA",
        description: "English Breakfast / Peppermint / Earl Grey / Jap Green",
        price: "4",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "HOME MADE LEMONADE W MINT",
        description: "",
        price: "6",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "VIET ICED COFFEE",
        description: "",
        price: "6",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "SOFT DRINK",
        description: "",
        price: "4.5",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "BEERS: ASAHI / HEINEKEN",
        description: "",
        price: "8",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "WINE GLASS",
        description: "HOUSE WHITE / RED",
        price: "8 / 10",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "WINE BOTTLE",
        description: "HOUSE WHITE / RED",
        price: "38 / 48",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
    ],
  },
];
