export const breakfast_menu = [
  {
    label: "BREAK FAST",
    menus: [
      {
        name: "TOAST",
        description: "Country white, dark wheat, Kalamata olive, Raisin Walnut",
        price: "5",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/toast.jpeg",
      },
      {
        name: "BACON & EGG PRESS",
        description: "Pendle Hill bacon double egg spinach chilli jam",
        price: "12",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "AVOCADO SMASH",
        description:
          "Yarra Feta citrus, roasted peanut, coriander, poached egg",
        price: "13",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/avoTomatoToast.jpeg",
      },
      {
        name: "THIS IS ME BREKKIE",
        description:
          "Crispy bacon, poached egg, potato rosti, avocado, butter mushrooms, sourdough",
        price: "22",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/thisIsBreakie.jpeg",
      },
      {
        name: "PARMESAN SCRAMBLED EGGS",
        description: "Truffle oil eggs shaved parmesan, dark sourdough",
        price: "16",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "CORN FRITTERS",
        description:
          "Crispy bacon, avocado, baby spinach, turmeric yoghurt, chilli jam",
        price: "21",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "EGGS ON TOAST",
        description: "Fried, scrambled, Poached",
        price: "10",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "EXTRAS",
        description:
          "Pendle Hill Bacon, sauntéed spinach, butter mushrooms, potato rosti, two eggs, avocado",
        price: "4",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
    ],
  },
];

export const lunch_menu = [
  {
    label: "SMALL THINGS",
    menus: [
      {
        name: "CRISPY PORK BELLY RICE PAPER ROLL",
        description: "Vermicelli Cucumber Pickled Carrot Peanut Sauce (2pc)",
        price: "8",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "",
      },
      {
        name: "LEMONGRASS BEEF RICE PAPER ROLLS W CUCUMBER",
        description: "Minted Iceberg Pickled Carrot Peanut Sauce (2pc)",
        price: "7.5",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "SEASONAL VEGETABLES & PUFF TOFU AVOCADO RICE PAPER ROLL (VG) (2PC)",
        description: "",
        price: "7.5",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "HERBY CHICKEN SESAME RICE PAPER ROLL W CUCUMBER PICICLED CARROT MAYO (2PC)",
        description: "",
        price: "7.5",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "HA DOAN’ S CHICKEN SPRING ROLLS NUOC CHAM (3PC)",
        description: "",
        price: "8",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "ROASTED DUCK RICE PAPER ROLL CUCUMBER VERMICELLI (2PC)",
        description: "",
        price: "9",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
    ],
  },
  {
    label: "VERMICELLI/SALADS",
    menus: [
      {
        name: "LOTUS STORY SALAD SHAVED CABBAGE",
        description:
          "Pickled Radish Peanuts Crispy Onion Aromatic Herbs Nuoc Cham – Crispy Tofu (GF) – Poached Chicken",
        price: "15",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "GRILLED BEEF AND SPRING ROLL VERMICELLI MINTED",
        description: "Iceberg Picicled Carrots Peanuts Scallions",
        price: "15",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "HERBY CHICON SUGARCANE PRAWN VERMICELLI MINTED",
        description: "Iceberg Picjcled Carrot Peanuts Scallions",
        price: "15",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "CRISPY TOFU & SEASONAL AVOCADO",
        description: "Bean Sprouts Peanuts Sweet Soy Sesame Dressing (Vg)",
        price: "15",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "HANOI TURMERIC FISH AND AVOCADO MINTED",
        description: "Iceberg Picjcled Carrots Peanuts Scallions",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "ROASTED PORK BELLY VERMICELLI AROMATIC HERBS SCALLIONS PEANUTS",
        description: "",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "FRESH BAKED BAGUETTES",
        description:
          "All Served With Fresh Mix Leaves Pickled Carrots Home Made Butter Peanut Sauce (P) Or House Soy (S) Original/Multigrain Bread, Chilli Or Coriander Optional",
        price: "11",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
    ],
  },
  {
    label: "NOODLES",
    menus: [
      {
        name: "HA DOAN’S 28 HOUR “PHO” BROTH – SLICED GRAIN FED BEEF I POACHED CHICKEN NOODLES AROMATIC HERBS (GF)",
        description: "",
        price: "15 / 17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "COMBINATION – BRISKET, SLICED BEEF, BEEF BALLS",
        description: "",
        price: "19",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "LOTUS STORY CHICKEN LAKSA RICE VERMICELLI & EGG NOODLE PUFF TOFU HINT AND FRIED SHALLOTS",
        description: "",
        price: "15",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "SPICY XO NOODLES CHICKEN, FRIED EGG, SEASONAL VEG CABBAGE HOUSE SOY EGG NOODLE HOUSE CHILLI OIL",
        description: "",
        price: "18",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "SESAME BEEF HOFUN, GAI LAN, CHIVES, BEANSPOUTS, HOUSE DARK SOY",
        description: "",
        price: "20",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "LOTUS STORY SINGAPORE NOODLES HOUSE CURRY PASTE",
        description: "Seasonal Vegetables Thin Rice Noodles Puff Tofu/Chicken",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
    ],
  },
  {
    label: "Rice",
    menus: [
      {
        name: "HA DOAN’S 28 HOUR “PHO” BROTH – SLICED GRAIN FED BEEF I POACHED CHICKEN NOODLES AROMATIC HERBS (GF)",
        description: "",
        price: "15 / 17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "COMBINATION – BRISKET, SLICED BEEF, BEEF BALLS",
        description: "",
        price: "19",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "LOTUS STORY CHICKEN LAKSA RICE VERMICELLI & EGG NOODLE PUFF TOFU HINT AND FRIED SHALLOTS",
        description: "",
        price: "15",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "SPICY XO NOODLES CHICKEN, FRIED EGG, SEASONAL VEG CABBAGE HOUSE SOY EGG NOODLE HOUSE CHILLI OIL",
        description: "",
        price: "18",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "SESAME BEEF HOFUN, GAI LAN, CHIVES, BEANSPOUTS, HOUSE DARK SOY",
        description: "",
        price: "20",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "LOTUS STORY SINGAPORE NOODLES HOUSE CURRY PASTE",
        description: "Seasonal Vegetables Thin Rice Noodles Puff Tofu/Chicken",
        price: "17",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
    ],
  },
];

export const coffee_menu = [
  {
    label: "COFFEE",
    menus: [
      {
        name: "COFFEE",
        description: "Extras: Shot / Syrup / Decaf / Soy",
        price: "4 / 4.5",
        sub_price: "0.5",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "TEA",
        description: "English Breakfast / Peppermint / Earl Grey / Jap Green",
        price: "4",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "HOME MADE LEMONADE W MINT",
        description: "",
        price: "6",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "VIET ICED COFFEE",
        price: "6",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "SOFT DRINK",
        price: "4.5",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "BEERS: ASAHI / HEINEKEN",
        price: "8",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "WINE GLASS",
        description: "HOUSE WHITE / RED",
        price: "8 / 10",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
      {
        name: "WINE BOTTLE",
        description: "HOUSE WHITE / RED",
        price: "38 / 48",
        sub_price: "",
        count: 0,
        option: "",
        imgSrc: "/menus/beefRiceRoll.jpeg",
      },
    ],
  },
];
